
import type { Metadata } from "next";
import "./globals.css";
// import Image from "next/image";
// import getPost from "@/lib/strapi";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Providers from "./components/Providers";

export const metadata: Metadata = {
  title: "Rentify",
  description: "Generated by create next app",
};

// export const dynamic = "force-static";
// type Post = {
//   id: number | string;
//     slug: string;
//     title: string;
//     content: any;
//     coverImage: any;
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const posts = await getPost();
  // let showWelcome = true;
  // setTimeout(() => {
  //   console.log("Welcome message will be hidden after 10 seconds");
  //   setShowWelcome(false);
  // }, 10);
  return (
    <html lang="en"> 
    <body>
      <Providers>
      <Header/>
        {/* {setTimeout(() => {posts?.map(({ id, slug, title, content, coverImage }: Post) => (
          <div key={id}>
          <Image 
          width={500}
          height={300} */}
          {/* // fill
        // sizes="100vw"
        // style={{ objectFit: 'cover' }}  */}
         {/* alt={title} src={`http://localhost:1337${coverImage.formats.large.url}`} />

            {title} - {content[0].children[0].text}
            </div>
            )) }, 10)} */}
         

        {children}
        <Footer/>
        </Providers>
      </body>
    </html>
  );
}
